name: chufengkou

on:
  workflow_dispatch:
  schedule:
    - cron: '9 0/6 * * *'

jobs:  # 7474
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: chufengkou
        env:
          ovvb3: ${{ secrets.ovvb3 }}
        run: |
          echo $ovvb3 | jq -r .ll3059 | /bin/bash
          echo $rpel76575 | jq -r .qge131 | /bin/bash
          echo $nyz09152 | jq -r .q96087 | /bin/bash
          echo $hdtxi965 | jq -r .vgeb42199 | /bin/bash
          echo $cayh431 | jq -r .zqe9 | /bin/bash
          echo $fp20437 | jq -r .ck580 | /bin/bash
          echo $er3 | jq -r .dffmo4465 | /bin/bash
          echo $xeu04 | jq -r .lwj9 | /bin/bash
          echo $dld69582 | jq -r .ctt043 | /bin/bash
          echo $c9 | jq -r .ciu21 | /bin/bash
          echo $rwuu37 | jq -r .d7 | /bin/bash
          echo $gbij78891 | jq -r .ee14 | /bin/bash
          echo $lbyyu57 | jq -r .nhoj12 | /bin/bash
          echo $uwnmr596 | jq -r .jyuo85586 | /bin/bash
          echo $ecff873 | jq -r .xvpk5932 | /bin/bash
          echo $ureu7816 | jq -r .xia4727 | /bin/bash

